### ISSUE TITLE
Gpu information

### ISSUE THREAD

**Issue by wh1ter0z** [koogar/Phat-Stats#1]
![20230913_210822](https://github.com/koogar/Phat-Stats/assets/69695347/026cd647-91f9-4af9-ac8e-5d7ad9f9da2e)
Help me 

Gpu power 
Total gpu mem
Gpu mem used
Shader ...

There is no info about them

**Comment by koogar** [comment]
Hi,

From what I can gather AMD may have changed something in later drivers.
Other hardware monitor programs have had issues also.

HardwareSerialMonitor user's the libraries from Open Hardware Monitor which
is very behind.

You could try using an earlier driver to see if this is the case, or
disable those stats in the phatstats config.
